package com.uplink.ulx.bridge.io.model;

public interface Packet {

    /**
     * Returns the packet's type, as represented by the {@link PacketType}
     * enumeration. These types are defined by convention, and can be used to
     * decode the packet's type from a binary encoding when the packet is
     * received.
     * @return The {@link Packet}'s type.
     */
    PacketType getType();

    /**
     * A {@link Packet}'s sequence identifier is a sequence number that is
     * generated by the packet's originator to identify the packet.
     * @return The {@link Packet}'s sequence identifier.
     */
    int getSequenceIdentifier();
}
